# Alacritty Configuration File
#
# For the full config documentation, check https://github.com/alacritty/alacritty

# Window Configuration
window:
  dynamic_title: true
  dimensions:
    columns: 100
    lines: 30

  padding:
    x: 10
    y: 10

  scrolling:
    history: 10000
    multiplier: 2

  font:
    normal:
      family: "MesloLGS NF"
      style: Regular

    bold:
      family: "MesloLGS NF"
      style: Bold

    italic:
      family: "MesloLGS NF"
      style: Italic

    size: 12.0

  draw_bold_text_with_bright_colors: false

# Window Background Opacity
background_opacity: 0.9

# Colors
colors:
  primary:
    background: "#282a36"
    foreground: "#f8f8f2"
    bright_foreground: "#ffffff"
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  search:
    matches:
      foreground: "#44475a"
      background: "#50fa7b"
    focused_match:
      foreground: "#44475a"
      background: "#ffb86c"

  footer_bar:
    background: "#282a36"
    foreground: "#f8f8f2"

  hints:
    start:
      foreground: "#282a36"
      background: "#f1fa8c"
    end:
      foreground: "#f1fa8c"
      background: "#282a36"

  line_indicator:
    foreground: None
    background: None

  selection:
    text: CellForeground
    background: "#44475a"

  normal:
    black: "#21222c"
    red: "#ff5555"
    green: "#50fa7b"
    yellow: "#f1fa8c"
    blue: "#bd93f9"
    magenta: "#ff79c6"
    cyan: "#8be9fd"
    white: "#f8f8f2"

  bright:
    black: "#6272a4"
    red: "#ff6e6e"
    green: "#69ff94"
    yellow: "#ffffa5"
    blue: "#d6acff"
    magenta: "#ff92df"
    cyan: "#a4ffff"
    white: "#ffffff"

# Key Bindings
key_bindings:
  - { key: J, mods: Alt, chars: "j" }
  - { key: K, mods: Alt, chars: "k" }
  - { key: H, mods: Alt, chars: "h" }
  - { key: L, mods: Alt, chars: "l" }
  - { key: T, mods: Alt, chars: "t" }
  - { key: W, mods: Alt|Shift, chars: "W" }
  - { key: P, mods: Alt, chars: "p" }
  - { key: N, mods: Alt, chars: "n" }
  - { key: D, mods: Alt, chars: "d" }
  - { key: E, mods: Alt, chars: "e" }
  - { key: X, mods: Alt|Shift, chars: "X" }
